cabal-version:      2.4
name:               haskell-gemini-bot
version:            0.1.0.0
author:             Igor Volokhov
maintainer:         your.email@example.com
extra-source-files: CHANGELOG.md

executable haskell-gemini-bot
    main-is:          Main.hs
    build-depends:
        base ^>=4.18.0.0,
        telegram-bot-simple >= 0.6.0,
        telegram-bot-api >= 7.4.5,
        process >= 1.6.9.0,
        text >= 2.0,
        filepath >= 1.4.2.1,
        directory >= 1.3.6.0,
        dotenv >= 0.9.0.2,
        temporary >= 1.3,
        data-default-class >= 0.1,
        bytestring >= 0.11

    hs-source-dirs:   app
    default-language: GHC2021